GET http://localhost:3090/subscribers/
###
GET http://localhost:3090/subscribers/5daf13c95bf0b86ff35c956a
###
POST http://localhost:3090/subscribers/
Content-Type: application/json

{
    "name" : "Joha Name",
    "subscribedToChannel" : "Cannel1"
}

###

DELETE http://localhost:3090/subscribers/5daf1244f1824b6f4452e428


###
PATCH http://localhost:3090/subscribers/5daf13c95bf0b86ff35c956a
Content-Type: application/json

{
    "name" : "Jane Doe"
}